Add webpage layout
limavfabio/summit-template pull request #1
Opened 2022-07-28 17:42 UTC by limavfabio

This PR implements a copy of the template for the 2015 CC Global Summit webpage made by Cindy Shin.

2022-07-28 19:24 UTC, keroloussamy requested changes
Hi @limavfabio, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Optional suggestions
_Check the comments under the review._

- [ ] x

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 19:24 UTC, keroloussamy commented on about.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
- [ ] Kindly there's a horizontal scrolling on your about page, kindly fix it to match the original design.

![image](https://user-images.githubusercontent.com/35535130/181617927-2947581b-f1f2-401f-bdaf-ee9fa6c17795.png)

2022-07-28 19:24 UTC, keroloussamy commented on about.html
> +      </footer>
- [ ] Kindly make the image smaller so you can give the text more space, to make your design much better.

![image](https://user-images.githubusercontent.com/35535130/181618407-b1be29ff-2761-423e-90e2-1f954c474d55.png)

2022-07-28 19:24 UTC, keroloussamy commented on index.html
> +              <a class="nav-link px-md-3 px-2" href="#">Sponsor</a>
- [ ] Kindly add the top short bar section with social media links, logout, and language links aligned to the right. To match the original layout.

![image](https://user-images.githubusercontent.com/35535130/181620631-d6cd8a0b-d5b5-479e-966f-2094b5ca688d.png)

2022-07-28 20:48 UTC, limavfabio commented
@keroloussamy It's done bro, can I just submit it, or do I have to wait for you to undo the approval?

2022-07-28 23:01 UTC, merged

2022-07-29 09:39 UTC, keroloussamy commented
Hello @limavfabio, Yes new everything is okay you can go forward.